saml:
  idp_entityid: http://www.okta.com/example
  sp_entityid: zabbix
  sso_url: https://example.okta.com/sso/saml
  username_attribute: usrEmail
  encrypt_nameid: 'NO'
  encrypt_assertions: 'YES'
  sign_messages: 'NO'
  sign_assertions: 'YES'
  sign_authn_requests: 'NO'
  sign_logout_requests: 'NO'
  sign_logout_responses: 'NO'
  provision_status: ENABLED
  group_name: groups
  user_username: firstName
  user_lastname: lastName
  disabled_user_group: Templar Disabled
  provision_groups:
  - name: zabbix-admins
    role: Super admin role
    user_groups:
    - Templar Users
  provision_media:
  - name: Email
    attribute: email
    type: Email
  scim_status: DISABLED
  saml_case_sensitive: 'YES'
