from __future__ import annotations

from zbxtemplar.zabbix.Inventory import InventoryField as _InventoryFieldBase


class InventoryField(_InventoryFieldBase):
    """Zabbix 7.4 host inventory field names."""

    TYPE = "type"
    TYPE_FULL = "type_full"
    NAME = "name"
    ALIAS = "alias"
    OS = "os"
    OS_FULL = "os_full"
    OS_SHORT = "os_short"
    SERIALNO_A = "serialno_a"
    SERIALNO_B = "serialno_b"
    TAG = "tag"
    ASSET_TAG = "asset_tag"
    MACADDRESS_A = "macaddress_a"
    MACADDRESS_B = "macaddress_b"
    HARDWARE = "hardware"
    HARDWARE_FULL = "hardware_full"
    SOFTWARE = "software"
    SOFTWARE_FULL = "software_full"
    SOFTWARE_APP_A = "software_app_a"
    SOFTWARE_APP_B = "software_app_b"
    SOFTWARE_APP_C = "software_app_c"
    SOFTWARE_APP_D = "software_app_d"
    SOFTWARE_APP_E = "software_app_e"
    CONTACT = "contact"
    LOCATION = "location"
    LOCATION_LAT = "location_lat"
    LOCATION_LON = "location_lon"
    NOTES = "notes"
    CHASSIS = "chassis"
    MODEL = "model"
    HW_ARCH = "hw_arch"
    VENDOR = "vendor"
    CONTRACT_NUMBER = "contract_number"
    INSTALLER_NAME = "installer_name"
    DEPLOYMENT_STATUS = "deployment_status"
    URL_A = "url_a"
    URL_B = "url_b"
    URL_C = "url_c"
    HOST_NETWORKS = "host_networks"
    HOST_NETMASK = "host_netmask"
    HOST_ROUTER = "host_router"
    OOB_IP = "oob_ip"
    OOB_NETMASK = "oob_netmask"
    OOB_ROUTER = "oob_router"
    DATE_HW_PURCHASE = "date_hw_purchase"
    DATE_HW_INSTALL = "date_hw_install"
    DATE_HW_EXPIRY = "date_hw_expiry"
    DATE_HW_DECOMM = "date_hw_decomm"
    SITE_ADDRESS_A = "site_address_a"
    SITE_ADDRESS_B = "site_address_b"
    SITE_ADDRESS_C = "site_address_c"
    SITE_CITY = "site_city"
    SITE_STATE = "site_state"
    SITE_COUNTRY = "site_country"
    SITE_ZIP = "site_zip"
    SITE_RACK = "site_rack"
    SITE_NOTES = "site_notes"
    POC_1_NAME = "poc_1_name"
    POC_1_EMAIL = "poc_1_email"
    POC_1_PHONE_A = "poc_1_phone_a"
    POC_1_PHONE_B = "poc_1_phone_b"
    POC_1_CELL = "poc_1_cell"
    POC_1_SCREEN = "poc_1_screen"
    POC_1_NOTES = "poc_1_notes"
    POC_2_NAME = "poc_2_name"
    POC_2_EMAIL = "poc_2_email"
    POC_2_PHONE_A = "poc_2_phone_a"
    POC_2_PHONE_B = "poc_2_phone_b"
    POC_2_CELL = "poc_2_cell"
    POC_2_SCREEN = "poc_2_screen"
    POC_2_NOTES = "poc_2_notes"
