"""Auto-generated. Templates/Applications."""
import json
from pathlib import Path

from zbxtemplar.zabbix.Template import Template

_loaded = {
    t["name"]: Template.from_dict(t)
    for t in json.loads((Path(__file__).parent / "data" / 'applications.json').read_text(encoding="utf-8"))
}


class Applications:
    """Templates/Applications"""
    Acronis_Cyber_Protect_Cloud_MSP_by_HTTP: Template = _loaded['Acronis Cyber Protect Cloud MSP by HTTP']
    Acronis_Cyber_Protect_Cloud_by_HTTP: Template = _loaded['Acronis Cyber Protect Cloud by HTTP']
    Apache_ActiveMQ_by_JMX: Template = _loaded['Apache ActiveMQ by JMX']
    Apache_Kafka_by_JMX: Template = _loaded['Apache Kafka by JMX']
    Apache_Tomcat_by_JMX: Template = _loaded['Apache Tomcat by JMX']
    Apache_by_HTTP: Template = _loaded['Apache by HTTP']
    Apache_by_Zabbix_agent: Template = _loaded['Apache by Zabbix agent']
    Apache_by_Zabbix_agent_active: Template = _loaded['Apache by Zabbix agent active']
    Aranet_Cloud: Template = _loaded['Aranet Cloud']
    Ceph_by_Zabbix_agent_2: Template = _loaded['Ceph by Zabbix agent 2']
    Cisco_Meraki_dashboard_by_HTTP: Template = _loaded['Cisco Meraki dashboard by HTTP']
    Cisco_Meraki_device_by_HTTP: Template = _loaded['Cisco Meraki device by HTTP']
    Cisco_Meraki_organization_by_HTTP: Template = _loaded['Cisco Meraki organization by HTTP']
    Cisco_SD_WAN_by_HTTP: Template = _loaded['Cisco SD-WAN by HTTP']
    Cisco_SD_WAN_device_by_HTTP: Template = _loaded['Cisco SD-WAN device by HTTP']
    Cloudflare_by_HTTP: Template = _loaded['Cloudflare by HTTP']
    Control_M_enterprise_manager_by_HTTP: Template = _loaded['Control-M enterprise manager by HTTP']
    Control_M_server_by_HTTP: Template = _loaded['Control-M server by HTTP']
    Docker_by_Zabbix_agent_2: Template = _loaded['Docker by Zabbix agent 2']
    Elasticsearch_Cluster_by_HTTP: Template = _loaded['Elasticsearch Cluster by HTTP']
    Envoy_Proxy_by_HTTP: Template = _loaded['Envoy Proxy by HTTP']
    Etcd_by_HTTP: Template = _loaded['Etcd by HTTP']
    Generic_Java_JMX: Template = _loaded['Generic Java JMX']
    GitHub_repository_by_HTTP: Template = _loaded['GitHub repository by HTTP']
    GitLab_by_HTTP: Template = _loaded['GitLab by HTTP']
    HAProxy_by_HTTP: Template = _loaded['HAProxy by HTTP']
    HAProxy_by_Zabbix_agent: Template = _loaded['HAProxy by Zabbix agent']
    Hadoop_by_HTTP: Template = _loaded['Hadoop by HTTP']
    HashiCorp_Consul_Cluster_by_HTTP: Template = _loaded['HashiCorp Consul Cluster by HTTP']
    HashiCorp_Consul_Node_by_HTTP: Template = _loaded['HashiCorp Consul Node by HTTP']
    HashiCorp_Nomad_Client_by_HTTP: Template = _loaded['HashiCorp Nomad Client by HTTP']
    HashiCorp_Nomad_Server_by_HTTP: Template = _loaded['HashiCorp Nomad Server by HTTP']
    HashiCorp_Nomad_by_HTTP: Template = _loaded['HashiCorp Nomad by HTTP']
    HashiCorp_Vault_by_HTTP: Template = _loaded['HashiCorp Vault by HTTP']
    IIS_by_Zabbix_agent: Template = _loaded['IIS by Zabbix agent']
    IIS_by_Zabbix_agent_active: Template = _loaded['IIS by Zabbix agent active']
    InfluxDB_by_HTTP: Template = _loaded['InfluxDB by HTTP']
    Jenkins_by_HTTP: Template = _loaded['Jenkins by HTTP']
    Jira_Data_Center_by_JMX: Template = _loaded['Jira Data Center by JMX']
    Kubernetes_API_server_by_HTTP: Template = _loaded['Kubernetes API server by HTTP']
    Kubernetes_Controller_manager_by_HTTP: Template = _loaded['Kubernetes Controller manager by HTTP']
    Kubernetes_Kubelet_by_HTTP: Template = _loaded['Kubernetes Kubelet by HTTP']
    Kubernetes_Scheduler_by_HTTP: Template = _loaded['Kubernetes Scheduler by HTTP']
    Kubernetes_cluster_state_by_HTTP: Template = _loaded['Kubernetes cluster state by HTTP']
    Kubernetes_nodes_by_HTTP: Template = _loaded['Kubernetes nodes by HTTP']
    Mantis_BT_by_HTTP: Template = _loaded['Mantis BT by HTTP']
    Memcached_by_Zabbix_agent_2: Template = _loaded['Memcached by Zabbix agent 2']
    Microsoft_365_reports_by_HTTP: Template = _loaded['Microsoft 365 reports by HTTP']
    Microsoft_Exchange_Server_2016_by_Zabbix_agent: Template = _loaded['Microsoft Exchange Server 2016 by Zabbix agent']
    Microsoft_Exchange_Server_2016_by_Zabbix_agent_active: Template = _loaded['Microsoft Exchange Server 2016 by Zabbix agent active']
    Microsoft_SharePoint_by_HTTP: Template = _loaded['Microsoft SharePoint by HTTP']
    NGINX_Plus_by_HTTP: Template = _loaded['NGINX Plus by HTTP']
    Nextcloud_by_HTTP: Template = _loaded['Nextcloud by HTTP']
    Nginx_by_HTTP: Template = _loaded['Nginx by HTTP']
    Nginx_by_Zabbix_agent: Template = _loaded['Nginx by Zabbix agent']
    Nginx_by_Zabbix_agent_active: Template = _loaded['Nginx by Zabbix agent active']
    Nutanix_Cluster_Prism_Element_by_HTTP: Template = _loaded['Nutanix Cluster Prism Element by HTTP']
    Nutanix_Host_Prism_Element_by_HTTP: Template = _loaded['Nutanix Host Prism Element by HTTP']
    Nutanix_Prism_Element_by_HTTP: Template = _loaded['Nutanix Prism Element by HTTP']
    Nvidia_by_Zabbix_agent_2: Template = _loaded['Nvidia by Zabbix agent 2']
    Nvidia_by_Zabbix_agent_2_active: Template = _loaded['Nvidia by Zabbix agent 2 active']
    OPNsense_by_SNMP: Template = _loaded['OPNsense by SNMP']
    OS_processes_by_Zabbix_agent: Template = _loaded['OS processes by Zabbix agent']
    OpenWeatherMap_by_HTTP: Template = _loaded['OpenWeatherMap by HTTP']
    PFSense_by_SNMP: Template = _loaded['PFSense by SNMP']
    PHP_FPM_by_HTTP: Template = _loaded['PHP-FPM by HTTP']
    PHP_FPM_by_Zabbix_agent: Template = _loaded['PHP-FPM by Zabbix agent']
    PHP_FPM_by_Zabbix_agent_active: Template = _loaded['PHP-FPM by Zabbix agent active']
    Proxmox_VE_by_HTTP: Template = _loaded['Proxmox VE by HTTP']
    RabbitMQ_cluster_by_HTTP: Template = _loaded['RabbitMQ cluster by HTTP']
    RabbitMQ_cluster_by_Zabbix_agent: Template = _loaded['RabbitMQ cluster by Zabbix agent']
    RabbitMQ_node_by_HTTP: Template = _loaded['RabbitMQ node by HTTP']
    RabbitMQ_node_by_Zabbix_agent: Template = _loaded['RabbitMQ node by Zabbix agent']
    Remote_Zabbix_proxy_health: Template = _loaded['Remote Zabbix proxy health']
    Remote_Zabbix_server_health: Template = _loaded['Remote Zabbix server health']
    Squid_by_SNMP: Template = _loaded['Squid by SNMP']
    Systemd_by_Zabbix_agent_2: Template = _loaded['Systemd by Zabbix agent 2']
    Travis_CI_by_HTTP: Template = _loaded['Travis CI by HTTP']
    TrueNAS_CORE_by_SNMP: Template = _loaded['TrueNAS CORE by SNMP']
    VMware: Template = _loaded['VMware']
    VMware_FQDN: Template = _loaded['VMware FQDN']
    VMware_Guest: Template = _loaded['VMware Guest']
    VMware_Hypervisor: Template = _loaded['VMware Hypervisor']
    Veeam_Backup_Enterprise_Manager_by_HTTP: Template = _loaded['Veeam Backup Enterprise Manager by HTTP']
    Veeam_Backup_and_Replication_by_HTTP: Template = _loaded['Veeam Backup and Replication by HTTP']
    Website_by_Browser: Template = _loaded['Website by Browser']
    Website_certificate_by_Zabbix_agent_2: Template = _loaded['Website certificate by Zabbix agent 2']
    Website_certificate_by_Zabbix_agent_2_active: Template = _loaded['Website certificate by Zabbix agent 2 active']
    WildFly_Domain_by_JMX: Template = _loaded['WildFly Domain by JMX']
    WildFly_Server_by_JMX: Template = _loaded['WildFly Server by JMX']
    Zabbix_agent: Template = _loaded['Zabbix agent']
    Zabbix_agent_active: Template = _loaded['Zabbix agent active']
    Zabbix_proxy_health: Template = _loaded['Zabbix proxy health']
    Zabbix_proxy_health_by_Zabbix_agent: Template = _loaded['Zabbix proxy health by Zabbix agent']
    Zabbix_proxy_health_by_Zabbix_agent_active: Template = _loaded['Zabbix proxy health by Zabbix agent active']
    Zabbix_server_health: Template = _loaded['Zabbix server health']
    Zabbix_server_health_by_Zabbix_agent: Template = _loaded['Zabbix server health by Zabbix agent']
    Zabbix_server_health_by_Zabbix_agent_active: Template = _loaded['Zabbix server health by Zabbix agent active']
    Zookeeper_by_HTTP: Template = _loaded['Zookeeper by HTTP']
